name: CI/CD Pipeline - Task List App

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      run_performance_tests:
        description: 'Run performance tests'
        type: boolean
        default: false
      performance_users:
        description: 'Number of users for performance test'
        default: '10'
      performance_duration:
        description: 'Duration of performance test (seconds)'
        default: '60'

env:
  PYTHON_VERSION: '3.10'
  FLASK_ENV: testing

jobs:
  # Job 1: Pruebas unitarias y lint
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 black pytest-cov

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

    # - name: Format check with black
    #   run: |
    #     black --check --diff .

    - name: Create templates directory
      run: mkdir -p templates

    - name: Create HTML template
      run: |
        cat > templates/index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="es">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Lista de Tareas</title>
            <style>
                body { font-family: Arial, sans-serif; margin: 40px; }
                .container { max-width: 600px; margin: 0 auto; }
                .task-form { margin-bottom: 20px; }
                .task-input { padding: 10px; width: 70%; }
                .btn { padding: 10px 20px; background: #007bff; color: white; border: none; cursor: pointer; }
                .task-item { padding: 10px; margin: 5px 0; background: #f8f9fa; border-radius: 5px; }
                .completed { text-decoration: line-through; opacity: 0.6; }
            </style>
        </head>
        <body>
            <div class="container">
                <h1>Lista de Tareas</h1>
                
                <div class="task-form">
                    <form action="{{ url_for('add_task') }}" method="POST">
                        <input type="text" name="task" class="task-input" placeholder="Nueva tarea..." required data-testid="task-input">
                        <button type="submit" class="btn" data-testid="add-task-btn">Agregar</button>
                    </form>
                </div>

                <div class="task-list">
                    {% if tasks %}
                        {% for task in tasks %}
                        <div class="task-item {% if task.completed %}completed{% endif %}" data-testid="task-item">
                            <span data-testid="task-text">{{ task.text }}</span>
                            <a href="{{ url_for('toggle_task', task_id=task.id) }}" data-testid="toggle-task-btn">
                                {% if task.completed %}Deshacer{% else %}Completar{% endif %}
                            </a>
                            <a href="{{ url_for('delete_task', task_id=task.id) }}" data-testid="delete-task-btn" 
                               onclick="return confirm('¿Eliminar esta tarea?')">Eliminar</a>
                        </div>
                        {% endfor %}
                    {% else %}
                        <div data-testid="empty-state">No hay tareas. ¡Agrega una nueva!</div>
                    {% endif %}
                </div>
            </div>
        </body>
        </html>
        EOF

    - name: Test Flask app startup
      run: |
        python -c "
        import sys
        sys.path.insert(0, '.')
        from app import app
        print('Flask app imported successfully')
        "

  # Job 2: Pruebas E2E
  e2e-tests:
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create templates directory and files
      run: |
        mkdir -p templates
        cat > templates/index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="es">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Lista de Tareas</title>
            <style>
                body { font-family: Arial, sans-serif; margin: 40px; }
                .container { max-width: 600px; margin: 0 auto; }
                .task-form { margin-bottom: 20px; }
                .task-input { padding: 10px; width: 70%; }
                .btn { padding: 10px 20px; background: #007bff; color: white; border: none; cursor: pointer; }
                .task-item { padding: 10px; margin: 5px 0; background: #f8f9fa; border-radius: 5px; }
                .completed { text-decoration: line-through; opacity: 0.6; }
            </style>
        </head>
        <body>
            <div class="container">
                <h1>Lista de Tareas</h1>
                
                <div class="task-form">
                    <form action="{{ url_for('add_task') }}" method="POST">
                        <input type="text" name="task" class="task-input" placeholder="Nueva tarea..." required data-testid="task-input">
                        <button type="submit" class="btn" data-testid="add-task-btn">Agregar</button>
                    </form>
                </div>

                <div class="task-list">
                    {% if tasks %}
                        {% for task in tasks %}
                        <div class="task-item {% if task.completed %}completed{% endif %}" data-testid="task-item">
                            <span data-testid="task-text">{{ task.text }}</span>
                            <a href="{{ url_for('toggle_task', task_id=task.id) }}" data-testid="toggle-task-btn">
                                {% if task.completed %}Deshacer{% else %}Completar{% endif %}
                            </a>
                            <a href="{{ url_for('delete_task', task_id=task.id) }}" data-testid="delete-task-btn" 
                               onclick="return confirm('¿Eliminar esta tarea?')">Eliminar</a>
                        </div>
                        {% endfor %}
                    {% else %}
                        <div data-testid="empty-state">No hay tareas. ¡Agrega una nueva!</div>
                    {% endif %}
                </div>
            </div>
        </body>
        </html>
        EOF

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable

    - name: Install Chrome dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb

    - name: Start Flask app in background
      run: |
        python app.py &
        echo $! > flask_app.pid
        sleep 10
      env:
        FLASK_ENV: testing
        PORT: 5000

    - name: Wait for Flask app to be ready
      run: |
        timeout 30s bash -c 'until curl -f http://localhost:5000/health; do sleep 2; done' || echo "Health check endpoint not available, continuing..."
        timeout 30s bash -c 'until curl -f http://localhost:5000/; do sleep 2; done'

    - name: Run E2E tests
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
        sleep 2
        python -m pytest tests/test_e2e.py -v --tb=short -x
      env:
        PYTHONPATH: .
        PYTEST_TIMEOUT: 300

    - name: Stop Flask app
      run: |
        if [ -f flask_app.pid ]; then
          kill $(cat flask_app.pid) || true
        fi
        pkill -f "python app.py" || true

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: e2e-test-results
        path: |
          pytest-report.html
          screenshots/
        retention-days: 7

  # Job 3: Pruebas de Performance
  performance-tests:
    runs-on: ubuntu-latest
    needs: [unit-tests, e2e-tests]
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.run_performance_tests == 'true' || github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create templates directory and files
      run: |
        mkdir -p templates
        cat > templates/index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="es">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Lista de Tareas</title>
            <style>
                body { font-family: Arial, sans-serif; margin: 40px; }
                .container { max-width: 600px; margin: 0 auto; }
                .task-form { margin-bottom: 20px; }
                .task-input { padding: 10px; width: 70%; }
                .btn { padding: 10px 20px; background: #007bff; color: white; border: none; cursor: pointer; }
                .task-item { padding: 10px; margin: 5px 0; background: #f8f9fa; border-radius: 5px; }
                .completed { text-decoration: line-through; opacity: 0.6; }
            </style>
        </head>
        <body>
            <div class="container">
                <h1>Lista de Tareas</h1>
                
                <div class="task-form">
                    <form action="{{ url_for('add_task') }}" method="POST">
                        <input type="text" name="task" class="task-input" placeholder="Nueva tarea..." required data-testid="task-input">
                        <button type="submit" class="btn" data-testid="add-task-btn">Agregar</button>
                    </form>
                </div>

                <div class="task-list">
                    {% if tasks %}
                        {% for task in tasks %}
                        <div class="task-item {% if task.completed %}completed{% endif %}" data-testid="task-item">
                            <span data-testid="task-text">{{ task.text }}</span>
                            <a href="{{ url_for('toggle_task', task_id=task.id) }}" data-testid="toggle-task-btn">
                                {% if task.completed %}Deshacer{% else %}Completar{% endif %}
                            </a>
                            <a href="{{ url_for('delete_task', task_id=task.id) }}" data-testid="delete-task-btn" 
                               onclick="return confirm('¿Eliminar esta tarea?')">Eliminar</a>
                        </div>
                        {% endfor %}
                    {% else %}
                        <div data-testid="empty-state">No hay tareas. ¡Agrega una nueva!</div>
                    {% endif %}
                </div>
            </div>
        </body>
        </html>
        EOF

    - name: Start Flask app for performance testing
      run: |
        python app.py &
        echo $! > flask_app_perf.pid
        sleep 5
      env:
        FLASK_ENV: production

    - name: Wait for Flask app to be ready
      run: |
        timeout 30s bash -c 'until curl -f http://localhost:5000/health || curl -f http://localhost:5000/; do sleep 2; done'

    - name: Run Locust performance tests
      run: |
        USERS=${{ github.event.inputs.performance_users || '10' }}
        DURATION=${{ github.event.inputs.performance_duration || '60' }}
        
        echo "Running performance tests with $USERS users for ${DURATION}s"
        
        locust -f tests/locustfile.py \
          --host=http://localhost:5000 \
          --users=$USERS \
          --spawn-rate=2 \
          --run-time=${DURATION}s \
          --html=performance-report.html \
          --csv=performance-results \
          --headless

    - name: Generate performance summary
      run: |
        echo "## Performance Test Results" > performance-summary.md
        echo "- Test Duration: ${{ github.event.inputs.performance_duration || '60' }} seconds" >> performance-summary.md
        echo "- Concurrent Users: ${{ github.event.inputs.performance_users || '10' }}" >> performance-summary.md
        echo "- Test Date: $(date)" >> performance-summary.md
        echo "" >> performance-summary.md
        
        if [ -f performance-results_stats.csv ]; then
          echo "### Request Statistics" >> performance-summary.md
          echo '```' >> performance-summary.md
          head -10 performance-results_stats.csv >> performance-summary.md
          echo '```' >> performance-summary.md
        fi
        
        if [ -f performance-results_failures.csv ]; then
          echo "### Failures" >> performance-summary.md
          echo '```' >> performance-summary.md
          cat performance-results_failures.csv >> performance-summary.md
          echo '```' >> performance-summary.md
        fi

    - name: Stop Flask app
      run: |
        if [ -f flask_app_perf.pid ]; then
          kill $(cat flask_app_perf.pid) || true
        fi
        pkill -f "python app.py" || true

    - name: Upload performance results
      uses: actions/upload-artifact@v4
      with:
        name: performance-test-results
        path: |
          performance-report.html
          performance-results*.csv
          performance-summary.md
        retention-days: 30

    - name: Comment performance results on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          
          if (fs.existsSync('performance-summary.md')) {
            const summary = fs.readFileSync('performance-summary.md', 'utf8');
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## Performance Test Results\n\n${summary}`
            });
          }

  # Job 4: Build y deploy (solo para main branch)
  deploy:
    runs-on: ubuntu-latest
    needs: [unit-tests, e2e-tests]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create deployment package
      run: |
        mkdir -p deploy
        cp -r *.py requirements.txt templates/ deploy/ 2>/dev/null || true
        cd deploy
        zip -r ../task-list-app.zip .

    - name: Upload deployment artifact
      uses: actions/upload-artifact@v4
      with:
        name: deployment-package
        path: task-list-app.zip
        retention-days: 90

    - name: Deployment summary
      run: |
        echo "## Deployment Ready" >> $GITHUB_STEP_SUMMARY
        echo "- All tests passed" >> $GITHUB_STEP_SUMMARY
        echo "- Deployment package created" >> $GITHUB_STEP_SUMMARY
        echo "- Ready for production deployment" >> $GITHUB_STEP_SUMMARY

  # Job 5: Reporte final
  report:
    runs-on: ubuntu-latest
    needs: [unit-tests, e2e-tests, performance-tests, deploy]
    if: always()

    steps:
    - name: Generate final report
      run: |
        echo "## CI/CD Pipeline Report" >> $GITHUB_STEP_SUMMARY
        echo "### Job Status Summary" >> $GITHUB_STEP_SUMMARY
        echo "- Unit Tests: ${{ needs.unit-tests.result }}" >> $GITHUB_STEP_SUMMARY
        echo "- E2E Tests: ${{ needs.e2e-tests.result }}" >> $GITHUB_STEP_SUMMARY
        echo "- Performance Tests: ${{ needs.performance-tests.result }}" >> $GITHUB_STEP_SUMMARY
        echo "- Deploy: ${{ needs.deploy.result }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Branch: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
        echo "### Commit: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
        echo "### Trigger: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY