name: CI/CD Pipeline - Task List App

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      run_performance_tests:
        description: 'Run performance tests'
        type: boolean
        default: false
      performance_users:
        description: 'Number of users for performance test'
        default: '10'
      performance_duration:
        description: 'Duration of performance test (seconds)'
        default: '60'

env:
  PYTHON_VERSION: '3.9'
  FLASK_ENV: testing

jobs:
  # Job 1: Pruebas unitarias y lint
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 black pytest-cov

    - name: Lint with flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

    - name: Format check with black
      run: |
        black --check --diff .

    - name: Create templates directory
      run: mkdir -p templates

    - name: Create HTML template
      run: |
        cat > templates/index.html << 'EOF'
        <!DOCTYPE html>
        <html>
        <head><title>Task List</title></head>
        <body>
        <!-- Template content will be populated during testing -->
        </body>
        </html>
        EOF

    - name: Test Flask app startup
      run: |
        timeout 10s python -c "
        import sys
        sys.path.insert(0, '.')
        from app import app
        print('Flask app imported successfully')
        " || echo "App validation completed"

  # Job 2: Pruebas E2E
  e2e-tests:
    runs-on: ubuntu-latest
    needs: unit-tests

    services:
      # No necesitamos base de datos para este proyecto simple

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create templates directory and files
      run: |
        mkdir -p templates
        # Copiar el template HTML desde el artifact (esto sería manual en un repo real)
        echo "Template would be copied here in a real repository"

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable

    - name: Install Chrome dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb

    - name: Start Flask app in background
      run: |
        python app.py &
        echo $! > flask_app.pid
        sleep 5
      env:
        FLASK_ENV: testing

    - name: Wait for Flask app to be ready
      run: |
        timeout 30s bash -c 'until curl -f http://localhost:5000/health; do sleep 2; done' || echo "Health check endpoint not available, continuing..."
        timeout 30s bash -c 'until curl -f http://localhost:5000/; do sleep 2; done'

    - name: Run E2E tests
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1920x1080x24 &
        python -m pytest tests/test_e2e.py -v --tb=short
      env:
        PYTHONPATH: .

    - name: Stop Flask app
      run: |
        if [ -f flask_app.pid ]; then
          kill $(cat flask_app.pid) || true
        fi
        pkill -f "python app.py" || true

    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: e2e-test-results
        path: |
          pytest-report.html
          screenshots/
        retention-days: 7

  # Job 3: Pruebas de Performance
  performance-tests:
    runs-on: ubuntu-latest
    needs: [unit-tests, e2e-tests]
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.run_performance_tests == 'true' || github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create templates directory and files
      run: |
        mkdir -p templates
        echo "Template setup for performance tests"

    - name: Start Flask app for performance testing
      run: |
        python app.py &
        echo $! > flask_app_perf.pid
        sleep 5
      env:
        FLASK_ENV: production

    - name: Wait for Flask app to be ready
      run: |
        timeout 30s bash -c 'until curl -f http://localhost:5000/health || curl -f http://localhost:5000/; do sleep 2; done'

    - name: Run Locust performance tests
      run: |
        # Configurar parámetros de prueba
        USERS=${{ github.event.inputs.performance_users || '10' }}
        DURATION=${{ github.event.inputs.performance_duration || '60' }}
        
        echo "Running performance tests with $USERS users for ${DURATION}s"
        
        # Ejecutar Locust en modo headless
        locust -f tests/locustfile.py \
          --host=http://localhost:5000 \
          --users=$USERS \
          --spawn-rate=2 \
          --run-time=${DURATION}s \
          --html=performance-report.html \
          --csv=performance-results \
          --headless

    - name: Generate performance summary
      run: |
        echo "## Performance Test Results" > performance-summary.md
        echo "- Test Duration: ${{ github.event.inputs.performance_duration || '60' }} seconds" >> performance-summary.md
        echo "- Concurrent Users: ${{ github.event.inputs.performance_users || '10' }}" >> performance-summary.md
        echo "- Test Date: $(date)" >> performance-summary.md
        echo "" >> performance-summary.md
        
        if [ -f performance-results_stats.csv ]; then
          echo "### Request Statistics" >> performance-summary.md
          echo '```' >> performance-summary.md
          head -10 performance-results_stats.csv >> performance-summary.md
          echo '```' >> performance-summary.md
        fi
        
        if [ -f performance-results_failures.csv ]; then
          echo "### Failures" >> performance-summary.md
          echo '```' >> performance-summary.md
          cat performance-results_failures.csv >> performance-summary.md
          echo '```' >> performance-summary.md
        fi

    - name: Stop Flask app
      run: |
        if [ -f flask_app_perf.pid ]; then
          kill $(cat flask_app_perf.pid) || true
        fi
        pkill -f "python app.py" || true

    - name: Upload performance results
      uses: actions/upload-artifact@v3
      with:
        name: performance-test-results
        path: |
          performance-report.html
          performance-results*.csv
          performance-summary.md
        retention-days: 30

    - name: Comment performance results on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          
          if (fs.existsSync('performance-summary.md')) {
            const summary = fs.readFileSync('performance-summary.md', 'utf8');
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 🚀 Performance Test Results\n\n${summary}`
            });
          }

  # Job 4: Build y deploy (solo para main branch)
  deploy:
    runs-on: ubuntu-latest
    needs: [unit-tests, e2e-tests]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create deployment package
      run: |
        mkdir -p deploy
        cp -r *.py requirements.txt templates/ deploy/ 2>/dev/null || true
        cd deploy
        zip -r ../task-list-app.zip .

    - name: Upload deployment artifact
      uses: actions/upload-artifact@v3
      with:
        name: deployment-package
        path: task-list-app.zip
        retention-days: 90

    - name: Deployment summary
      run: |
        echo "## 🚀 Deployment Ready" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ All tests passed" >> $GITHUB_STEP_SUMMARY
        echo "- 📦 Deployment package created" >> $GITHUB_STEP_SUMMARY
        echo "- 🔗 Ready for production deployment" >> $GITHUB_STEP_SUMMARY

  # Job 5: Reporte final
  report:
    runs-on: ubuntu-latest
    needs: [unit-tests, e2e-tests, performance-tests, deploy]
    if: always()

    steps:
    - name: Generate final report
      run: |
        echo "## 📊 CI/CD Pipeline Report" >> $GITHUB_STEP_SUMMARY
        echo "### Job Status Summary" >> $GITHUB_STEP_SUMMARY
        echo "- Unit Tests: ${{ needs.unit-tests.result }}" >> $GITHUB_STEP_SUMMARY
        echo "- E2E Tests: ${{ needs.e2e-tests.result }}" >> $GITHUB_STEP_SUMMARY
        echo "- Performance Tests: ${{ needs.performance-tests.result }}" >> $GITHUB_STEP_SUMMARY
        echo "- Deploy: ${{ needs.deploy.result }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Branch: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
        echo "### Commit: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
        echo "### Trigger: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY